FROM	alpine

RUN		apk add mariadb mariadb-client && \
		mkdir -p /run/mysqld/

# COPY	/srcs/telegraf.conf		/etc/telegraf/
COPY	/srcs/my.cnf			/etc/
COPY	/srcs/start.sh			/

EXPOSE 3306

ENTRYPOINT	sh start.sh
