FROM	alpine

# Install tools
RUN		apk update && \
		apk add --no-cache nginx openssl wget php7-fpm php7-common php7-iconv php7-json php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom && \
		rm -f /etc/nginx/conf.d/default.conf && \
		mkdir -p /run/nginx

RUN		apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache

WORKDIR	/tmp/
RUN		wget https://ja.wordpress.org/latest-ja.tar.gz \
		&& tar -xvzf latest-ja.tar.gz \
		&& mv wordpress /var/www/

WORKDIR	/
RUN		mkdir /etc/nginx/ssl \
		&& openssl genrsa -out /etc/nginx/ssl/private.key 2048 \
		&& openssl req -new -key /etc/nginx/ssl/private.key -out /etc/nginx/ssl/server.csr -subj "/C=JP/ST=Tokyo/L=Roppongi/O=42tokyo/OU=/CN=localhost" \
		&& openssl x509 -days 365 -req -signkey /etc/nginx/ssl/private.key -in /etc/nginx/ssl/server.csr -out /etc/nginx/ssl/server.crt


COPY	/srcs/telegraf.conf			/etc/telegraf/
COPY	/srcs/wp-nginx.conf			/etc/nginx/conf.d/default.conf
COPY	/srcs/wp-config.php			/var/www/wordpress/
COPY	/srcs/start.sh				/
COPY	/srcs/healthcheck.sh		/

EXPOSE	5050

ENTRYPOINT sh start.sh
